{% set name = "geoapps-utils" %}
{% set version = "0.3.0" %}
{% set python_min = "3.10" %}
{% set python_max = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 4671fc21594f465fe3975ffba037a4a053e63d7038aca6fbcf5da0913532fcc2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<{{ python_max }}
    - numpy >=1.23.5,<1.24.0
    - pydantic >=2.5.2,<2.6.0
    - scipy >=1.10.1,<1.11.0
    - geoh5py >=0.9.0,<0.10.0
    - h5py >=3.2.1,<4.0.0
    - pillow >=10.3.0,<10.4.0
  run_constrained:
    - dash >=2.12.0,<3.0.0
    - flask >=3.0.3,<4.0.0
    - pyqtwebengine >=5.15.2,<5.16.0,<5.15.7
    - pyside2 >=5.15.2,<5.16.0

test:
  imports:
    - geoapps_utils
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'Provides utility functions used by geoapps.'
  description: |
    The geoapps-utils package provides utility functions used by 
    (geoapps)<https://github.com/MiraGeoscience/geoapps>.
  license: MIT
  license_file: 
    - LICENSE
  dev_url: https://github.com/MiraGeoscience/geoapps-utils

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
