schema_version: 1

context:
  name: geoapps-utils
  version: "0.6.0"
  python_min: '3.10'
  module_name: ${{ name|lower|replace("-", "_") }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: eb21568d0da415b575ef6648a75c775b99a22adcf371e957df1b3167abc8811d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.8.0
    - poetry-dynamic-versioning >=1.9, 1.*
    - setuptools
  run:
    - python >=${{ python_min }}
    # Mira packages
    - geoh5py >=0.12.0, 0.12.*
    # direct dependencies
    - numpy 1.26*
    - pydantic 2.11.*
    - scipy 1.14.*
    - matplotlib-base >=3.8.4, 3.8.*


tests:
  - python:
      imports:
        - ${{ module_name }}
        - ${{ module_name }}._version
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/
  - package_contents:
      files:
        - site-packages/${{ module_name }}/_version.py

about:
  summary: Utility functions to build applications supported by Mira Geoscience.
  description: |
    The geoapps-utils package provides utility functions used by Python applications
    supported by [Mira Geoscience](https://www.mirageoscience.com/mining-industry-software/geoscience-analyst/python-integration/).
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/geoapps-utils

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
