schema_version: 1

context:
  name: geoapps-utils
  version: 0.4.0
  python_min: 3.10
  python_max: 3.11

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: d441ac5d566a5d11a5f32bbacc75c8a8d5f8a23749b0802a54a73c97405e2cf6

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - numpy >=1.26.0,<1.27.0
    - pydantic >=2.5.2,<2.6.0
    - scipy >=1.14.0,<1.15.0
    - geoh5py >=0.10.0rc1,<0.11.0a.dev
    - h5py >=3.2.1,<4.0.0
    - pillow >=10.3.0,<10.4.0

tests:
  - python:
      imports:
        - geoapps_utils
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  summary: Provides utility functions used by geoapps.
  description: |
    The geoapps-utils package provides utility functions used by
    (geoapps)<https://github.com/MiraGeoscience/geoapps>.
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/geoapps-utils

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
