schema_version: 1

context:
  name: geoapps-utils
  version: "0.5.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/MiraGeoscience/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 39bfba2144fa1cc52bb7c0940e1ba229c2d94f6fd9896d636d05cde4e90a983d

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    # Mira packages
    - geoh5py >=0.10.0,<0.11.dev
    # direct dependencies
    - numpy >=1.26.0,<1.27.dev
    - pydantic >=2.5.2,<3.0.dev
    - scipy >=1.14.0,<1.15.dev

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - geoapps_utils
      pip_check: true
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
    files:
      source:
        - tests/

about:
  summary: Utility functions to build applications supported by Mira Geoscience.
  description: |
    The geoapps-utils package provides utility functions used by Python applications
    supported by [Mira Geoscience](https://www.mirageoscience.com/mining-industry-software/geoscience-analyst/python-integration/).
  license: MIT
  license_file:
    - LICENSE
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/geoapps-utils

extra:
  recipe-maintainers:
    - conda-forge/geoh5py
